apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend
  namespace: my-expense
data: 
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-expense
  labels:
    app: nodejs
    tier: backend
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nodejs
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:{{.Values.deployment.version}}
        envFrom:
        - configMapRef:
            name: backend