apiVersion: v1
kind: Service
metadata: 
  name: backend
  namespace: expense
spec:
  selector:
    app: nodejs
    tier: backend
    project: expense
  ports:
  - name: backend-service-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}