apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-expense
  labels:
    app: html
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: html
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: html
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          # limits is greater than or equal to requests
          limits:
            cpu: 100m
            memory: 128Mi"
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: my-expense
spec:
  type: LoadBalancer
  selector:
    app: html
    tier: web
    project: expense
  ports:
  - name: frontend-service-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: my-expense
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10