apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app: my-app
spec:
  clusterIP: None # Makes the service headless
  selector:
    app: my-app
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-headless # Ties the StatefulSet to the headless service
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: mysql
          image: joindevops/mysql:v1
          ports:
            - containerPort: 3306
              name: tcp
          volumeMounts:
            - name: my-pvc
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: my-pvc
      spec:
        storageClassName: "ebs-sc"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi