apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: my-expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:{{.Values.deployment.version}}