apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-service-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}