apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::423623871433:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-s8nBU5zMkhoz
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::423623871433:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-23T15:17:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1476"
  uid: eb317285-76c1-4af0-b837-a7d54aff36fa