apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: html
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: html
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: html
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:{{.Values.deployment.version}}
        resources:
          requests:
            memory: "8Mi"     # Minimum amount of memory the container will need
            cpu: "50m"        # Minimum amount of CPU the container will need
          limits:
            memory: "8Mi"    # Maximum amount of memory the container can use
            cpu: "50m"