apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: html
    tier: web
    project: expense
  ports:
  - name: frontend-service-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}